language: php
php:
    - 5.6

install:
    - composer install
    - npm install acorn

script:
    - phpunit
    - sh noauto/acorn.sh

after_script:
    - vendor/bin/test-reporter

addons:
    code_climate:
        repo_token: 81f8a04e131cc7b92250685a363eee7f12f7de5a036228b9d03551e0040eab62
